import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Header } from "../components/header";
import { GeistSans } from "geist/font/sans";
import Footer from "@/components/footer";
import { SignedIn, SignedOut, useAuth } from "@clerk/nextjs";
import DashNav from "@/components/dash-nav";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <SignedIn>
            <div
              className={cn(
                "rounded-md flex flex-col md:flex-row bg-gray-100 dark:bg-neutral-800 w-full flex-1 mx-auto border border-neutral-200 dark:border-neutral-700 overflow-hidden",
                "h-screen"
              )}
            >
              <DashNav />
              <main className="rounded-tl-2xl bg-white container mx-auto p-4">{children}</main>
            </div>
          </SignedIn>
          <SignedOut>
            <Header />
            <div className="flex min-h-screen w-full">
              <main className="container mx-auto p-4">{children}</main>
            </div>
            <Footer />
          </SignedOut>
        </Providers>
      </body>
    </html>
  );
}
